server:
  port: 5500

spring:
  application:
    name: Money Transfer and Transactional Service(MTSS)

app:
  logging:
    file-path: logs/transfer.log
  commission:
    rate: 0.01
    min: 0.00
    currency: RUB
  verification:
    code-length: 4
    default-code: "0000"
  limits:
    max-transfer-amount: 100000000
    min-transfer-amount: 100